package com.ftn.szz.model.enums;

public enum EProfession {
    ADMINISTRATION,
    ECONOMICS_FINANCE_AND_INSURANCE,
    ELECTRICAL_ENGINEERING_AND_TELECOMMUNICATIONS,
    MEDICINE,
    ARCHITECTURE_CONSTRUCTION_AND_GEODESY
}
